from selenium import webdriver
import time

driver = webdriver.Chrome()
driver.get('https://youtube.com')

searchbox = driver.find_element_by_xpath('//*[@id="search"]')
searchbox.send_keys('P')
time.sleep(0.5)
searchbox = driver.find_element_by_xpath('//*[@id="search"]')
searchbox.send_keys('e')
time.sleep(0.5)
searchbox = driver.find_element_by_xpath('//*[@id="search"]')
searchbox.send_keys('w')
time.sleep(0.5)
searchbox = driver.find_element_by_xpath('//*[@id="search"]')
searchbox.send_keys('D')
time.sleep(0.5)
searchbox = driver.find_element_by_xpath('//*[@id="search"]')
searchbox.send_keys('i')
time.sleep(0.5)
searchbox = driver.find_element_by_xpath('//*[@id="search"]')
searchbox.send_keys('e')
time.sleep(0.5)
searchbox = driver.find_element_by_xpath('//*[@id="search"]')
searchbox.send_keys('P')
time.sleep(0.5)
searchbox = driver.find_element_by_xpath('//*[@id="search"]')
searchbox.send_keys('i')
time.sleep(0.5)
searchbox = driver.find_element_by_xpath('//*[@id="search"]')
searchbox.send_keys('e')
time.sleep(0.5)

searchButton = driver.find_element_by_xpath('//*[@id="search-icon-legacy"]')
searchButton.click()

subscribeButton = driver.find_element_by_xpath(')
subscribeButton.click()